#!/usr/bin/env python
# encoding: UTF8

descr = {
    'opt': 'Test new optimization...',
    'others': 'Additional columns',
    'ndesi': 'Number of decimals in output',
    'order': 'Order in the output parameters',
    'm_step': 'Resolution in magnitude prior interpolation',
    'output': 'Output file',
    'D_tel': 'Telescope diameter',
    'aperture': 'Aperture',
    'scale': 'Scale',
    'n_exp': 'Number of exposures',
    'RN': 'Readout noise',

    'trays': 'Tray layout.',
    'exp_trays': 'Exposure in different trays',
    'vign': 'Vignetting (center, peripheral, corner)',
    'sky_spec': 'Sky spectrum.',
    'add_noise': 'Add noise to the magnitudes.',
    'old_model': 'Use the BPZ model for observed magnitudes.',

    'ab_tmp': 'TEMPORARY',
    'zmax_ab': 'Maximum redshift in AB files',
    'dz_ab': 'Redshift step in AB files',
    'prior': 'Which priors to use',
    'train': 'Training set',
    'norm_flux': 'Normalize flux in a given filter.',
    'ab_dir': 'Cache directory for model magnitudes.',
    'filter_dir': 'Filter response directory.',
    'sed_dir': 'Template directory.',
    'p_min': 'Minimum probability in fraction of the peak.',
    'mag': 'Is the input data in magnitudes?',
    'spectra': 'Templates to use',
    'get_z': 'Calculate the photo-z',
    'use_par': 'Use parallel threads',
    'nthr': 'Numbers of thread to use.',
    'columns': 'Columns file',
    'merge_peaks': 'No idea (not used)',
    'interactive': 'No idea (not used)',
    'plots': 'No idea (not used)',
    'probs_lite': 'No idea (not used)',
    'add_spec_prob': 'No idea (not used)',
    'zc': 'No idea (not used)',
    'nmax': 'No idea (not used)',
    'probs': 'Output the full probablitiy distribution (not used)',
    'probs2': 'Output the probablitiy distribution p(z, T) (not used)',
    'convolve_p': 'Convolve the photo-z with a gaussian error (not used)',
    'photo_errors': 'Determine confidence interval from only photo-z errors (not used)',
    'z_thr': 'Integrate the probability when z_thr < z (not used)',
    'color': 'Instead of magnitudes, use colors (not used)',
    'zp_offsets': 'Additional magnitude offset.',
    'ntypes': 'Number of spectras for different types.',
    'madau': 'Use Madau correction.',
    'new_ab': 'Force regeneration of AB file.',
    'exclude': 'Filters to exclude for analysis.',
    'zmin': 'Minimum redshift',
    'zmax': 'Maximum redshift',
    'unobs': 'Value indicating unobserved magnitudes',
    'undet': 'Value indicating undetected magnitudes',
    'delta_m_0': 'Offset in m_0',
    'n_peaks': 'Number of peaks to output',
    'verbose': 'Output level',
    'min_magerr': 'Minimum error in the magnitudes.',
    'catalog': 'Input galaxy catalog.',
    'interp': 'Number of interpolation between templates.',
    'prior': 'Name of prior module',
    'dz': 'Redshift resolution in chi2 estimation',
    'odds': 'Odds',
    'min_rms': 'Intrinsic photo-z scatter.',
    'spectra': 'List of spectras'}
